//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlUtilities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankHolidays
    {
        public int Id { get; set; }
        public System.DateTime BankHolidayDate { get; set; }
        public string BankHolidayDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
